apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zurg
spec:
  defaultBackend:
    service:
      name: zurg
      port:
        number: 9999
  ingressClassName: tailscale
  tls:
    - hosts:
        - zurg
