---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
components:
  - ../../components/common
resources:
  - ./coredns/ks.yaml
  # - ./metrics-server/ks.yaml
  # - ./reloader/ks.yaml
  # - ./descheduler/ks.yaml
  # - ./node-feature-discovery/ks.yaml
  # - ./snapshot-controller/ks.yaml

  # - ./headlamp/ks.yaml
  # - ./cilium/ks.yaml
  # - ./flannel/ks.yaml
  # - ./intel-device-plugin-operator/ks.yaml
  # - ./spegel/ks.yaml
