---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "${APP}-volsync-remote"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: "${APP}-volsync-secret"
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: "{{ .REPOSITORY_TEMPLATE }}/${APP}"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"

        # FTPS
        RCLONE_CONFIG_BACKUP_TYPE: sftp
        RCLONE_CONFIG_BACKUP_HOST: "{{ .BACKUP_HOST }}"
        RCLONE_CONFIG_BACKUP_USER: "{{ .BACKUP_USER }}"
        RCLONE_CONFIG_BACKUP_KEY_PEM: "{{ .KEY_PEM }}"
        RCLONE_CONFIG_BACKUP_SHELL_TYPE: "unix"
        RCLONE_CONFIG_BACKUP_MD5SUM_COMMAND: "none"
        RCLONE_CONFIG_BACKUP_SHA1SUM_COMMAND: "none"
  dataFrom:
    - extract:
        key: restic-netdynamics #  # The key of the secret in the external store
