---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: symlinks-test
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-filesystem
