---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: headlamp
spec:
  interval: 1h
  url: https://kubernetes-sigs.github.io/headlamp/
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app headlamp
spec:
  driftDetection:
    mode: enabled
  interval: 30m
  chart:
    spec:
      chart: headlamp
      version: 0.30.1
      sourceRef:
        kind: HelmRepository
        name: headlamp
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        external-dns.alpha.kubernetes.io/target: "480p.com"
        cert-manager.io/cluster-issuer: letsencrypt-production
        traefik.ingress.kubernetes.io/router.middlewares: network-authentik@kubernetescrd

      hosts:
        - host: &host "{{ .Release.Name }}.480p.com"
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: app
                port: *port
      tls:
        - hosts:
            - *host
          secretName: "{{ .Release.Name }}-tls"
    podAnnotations:
      reloader.stakater.com/auto: "true"
    fullnameOverride: headlamp
    initContainers:
      - image: ghcr.io/headlamp-k8s/headlamp-plugin-flux:v0.2.0@sha256:6727bb58c95feef9f62f8fe125c244601d31ca62eab546b0f88c045560ed33de
        command:
          - /bin/sh
          - -c
          - mkdir -p /build/plugins && cp -r /plugins/* /build/plugins/
        name: headlamp-plugins
        volumeMounts:
          - mountPath: /build/plugins
            name: headlamp-plugins
    config:
      pluginsDir: /build/plugins
    serviceAccount:
      create: true
      name: headlamp-admin
    persistentVolumeClaim:
      enabled: true
      size: 1Gi
      accessModes:
        - ReadWriteOnce
      storageClassName: ceph-block
    volumeMounts:
      - mountPath: /build/plugins
        name: headlamp-plugins
    volumes:
      - name: headlamp-plugins
        emptyDir: {}
