---
originRequest:
  originServerName: "external.${SECRET_DOMAIN}"

ingress:
  - hostname: "${SECRET_DOMAIN}"
    # service: &svc https://external-ingress-nginx-controller.network.svc.cluster.local:443
    service: &svc http://external-ingress-nginx-controller.network.svc.cluster.local:80
  - hostname: "*.${SECRET_DOMAIN}"
    service: *svc
  - service: http_status:404
