---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: alertmanager-secret
    template:
      data:
        ALERTMANAGER_HEALTHCHECKS_URL: "{{ .ALERTMANAGER_HEALTHCHECKS_URL }}"
        TELEGRAM_BOT_TOKEN: "{{ .BOT_TOKEN }}"
        TELEGRAM_CHAT_ID: "{{ .CHAT_ID }}"
  dataFrom:
    - extract:
        key: telegram_token
    - extract:
        key: alertmanager
