---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
components:
  - ../../components/common
resources:
  - ./symlinks/ks.yaml
  - ./csi-rclone-secret.sops.yaml
  - ./pvc-rclone.yaml
  - ./debug-media/ks.yaml
  - ./decypharr/ks.yaml
  - ./warp/ks.yaml
  - ./plex/ks.yaml
  # - ./sonarr/ks.yaml
  # - ./sonarr4k/ks.yaml
  # - ./radarr/ks.yaml
  # - ./radarr4k/ks.yaml
  # - ./rdtclient/ks.yaml
  - ./prowlarr/ks.yaml
  # - ./bazarr/ks.yaml
  # - ./jellyseerr/ks.yaml
  # - ./recyclarr/ks.yaml
  # - ./tautulli/ks.yaml
  # - ./autosync/ks.yaml
  # - ./huntarr/ks.yaml
