---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
components:
  - ../../components/common
resources:
  - ./symlinks/ks.yaml
  - ./csi-rclone-secret.sops.yaml
  - ./pvc-rclone.yaml
  - ./decypharr/ks.yaml
  - ./warp/ks.yaml
  - ./plex/ks.yaml
  - ./tautulli/ks.yaml
  - ./sonarr/ks.yaml
  - ./sonarr4k/ks.yaml
  - ./radarr/ks.yaml
  - ./radarr4k/ks.yaml
  - ./prowlarr/ks.yaml
  - ./jellyseerr/ks.yaml
  - ./autosync/ks.yaml
  - ./profilarr/ks.yaml
  - ./huntarr/ks.yaml

  - ./seasonarr/ks.yaml

  - ./debug-media/ks.yaml
  # - ./huntarr4k/ks.yaml
  # - ./recyclarr/ks.yaml
  # - ./rdtclient/ks.yaml
  #   - ./bazarr/ks.yaml
