---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job.longhorn.io/backup-daily: enabled
    recurring-job.longhorn.io/snapshot-hourly: enabled
  name: pvc-symlinks
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-rc3
  resources:
    requests:
      storage: 2Gi
