---
creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    age: "age127k9xyyfucv49hz4lgqyxhv3egulzyuvjaq9z099027jynczvslqvkn9cg"
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age127k9xyyfucv49hz4lgqyxhv3egulzyuvjaq9z099027jynczvslqvkn9cg"
stores:
  yaml:
    indent: 2
