---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app symlinks
  namespace: &namespace media
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    # - name: nfs-ganesha
    #   namespace: nfs-ganesha
  interval: 1h
  path: ./kubernetes/apps/media/symlinks/app
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 5Gi
      VOLSYNC_STORAGECLASS: ceph-filesystem
      VOLSYNC_ACCESSMODES: ReadWriteMany
      VOLSYNC_SNAPSHOTCLASS: ceph-filesystem-snapshot
      VOLSYNC_CACHE_CAPACITY: 5Gi
      VOLSYNC_CACHE_SNAPSHOTCLASS: ceph-filesystem
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
  # components:
  # - ../../../../components/volsync
