---
groups:
  - name: sonarr4k
    rules:
      - alert: sonarr4kDatabaseIsLocked
        expr: |
          sum by (app) (count_over_time({app=~"sonarr4k"} |~ "(?i)database is locked"[5m])) > 0
        for: 5m
        annotations:
          summary: >-
            {{ $labels.app }} is experiencing database issues
        labels:
          severity: critical

      - alert: sonarr4kDatabaseIsMalformed
        expr: |
          sum by (app) (count_over_time({app=~"sonarr4k"} |~ "(?i)database disk image is malformed"[5m])) > 0
        for: 5m
        annotations:
          summary: >-
            {{ $labels.app }} is experiencing database issues
        labels:
          severity: critical
