# Forward authentication to example.com
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oauth-auth-redirect
spec:
  forwardAuth:
    address: https://oauth2-proxy.oauth2-proxy.svc.cluster.local/
    # address: https://oauth2-proxy.480p.com/
    trustForwardHeader: true
    authResponseHeaders:
      - X-Auth-Request-Access-Token
      - Authorization