# Forward authentication to example.com
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oautherrors
spec:
    oauth-errors:
      errors:
        status:
          - "401-403"
        service: oauth2-proxy
        query: "/oauth2/sign_in?rd={url}"
