---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kube-vm-stack
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.50.1
  url: oci://ghcr.io/victoriametrics/helm-charts/victoria-metrics-k8s-stack
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-vm-stack
spec:
  driftDetection:
    mode: enabled
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: kube-vm-stack

  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    nameOverride: vmstack

    grafana:
      enabled: false
      # forceDeployDatasource: true
    crds:
      enabled: true
    prometheus-operator-crds:
      enabled: true
    victoria-metrics-operator:
      enabled: true
      crd:
        create: true
        cleanup:
          enabled: true
      operator:
        disable_prometheus_converter: false
        enable_converter_ownership: true
    defaultDashboards:
      enabled: true
      grafanaOperator:
        enabled: true
        spec:
          instanceSelector:
            matchLabels:
              dashboards: grafana
          allowCrossNamespaceImport: true
    defaultDatasources:
      grafanaOperator:
        enabled: true
        annotations: {}
        spec:
          instanceSelector:
            matchLabels:
              dashboards: grafana
          allowCrossNamespaceImport: true
      victoriametrics:
        # -- Create per replica prometheus compatible datasource
        perReplica: false
        # -- List of prometheus compatible datasource configurations.
        # VM `url` will be added to each of them in templates.
        datasources:
          - name: VictoriaMetrics
            type: prometheus
            access: proxy
            isDefault: true
          - name: VictoriaMetrics (DS)
            isDefault: false
            access: proxy
            type: victoriametrics-metrics-datasource
    defaultRules:
      create: false
    vmsingle:
      enabled: true
    alertmanager:
      enabled: true
    vmalert:
      enabled: true
    vmagent:
      enabled: true
    prometheus-node-exporter:
      enabled: false
    kube-state-metrics:
      enabled: false
    kubelet:
      enabled: false
      cadvisor: false
      probes: false
    kubeApiServer:
      enabled: false
    kubeControllerManager:
      enabled: false
    kubeDns:
      enabled: false
    coreDns:
      enabled: false
    kubeEtcd:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeProxy:
      enabled: false
