# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: piraeus-charts
spec:
  interval: 5m
  url: https://piraeus.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app snapshot-controller
spec:
  driftDetection:
    mode: enabled
  interval: 30m
  chart:
    spec:
      chart: snapshot-controller
      version: 4.0.2
      sourceRef:
        kind: HelmRepository
        name: piraeus-charts
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
