---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: authentik-postgresql
    template:
      data:
        AUTHENTIK_SECRET_KEY: "{{ .AUTHENTIK_SECRET_KEY }}"
        AUTHENTIK_POSTGRESQL__PASSWORD: "{{ .AUTHENTIK_PASSWORD }}"
        AUTHENTIK_POSTGRESQL__USER: "{{ .AUTHENTIK_USER }}"
        # Add standard PostgreSQL environment variables
        POSTGRES_PASSWORD: "{{ .AUTHENTIK_PASSWORD }}"
        POSTGRES_POSTGRES_PASSWORD: "{{ .AUTHENTIK_PASSWORD }}"
        POSTGRES_USER: "{{ .AUTHENTIK_USER }}"
  dataFrom:
    - extract:
        key: authentik
