---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: authentik
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2025.4.1
  url: oci://ghcr.io/goauthentik/helm-charts/authentik
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app authentik
spec:
  driftDetection:
    mode: enabled
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: authentik
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    global:
      podAnnotations:
        reloader.stakater.com/auto: "true"
      deploymentStrategy:
        type: RollingUpdate
      envFrom:
        - secretRef:
            name: authentik-postgresql
    authentik:
      redis:
        host: dragonfly.dragonfly.svc.cluster.local
        port: 6379
        db: 1
    postgresql:
      enabled: true
      envFrom:
        - secretRef:
            name: authentik-postgresql
      primary:
        persistence:
          existingClaim: authentik
    server:
      replicas: 2
      resources:
        requests:
          cpu: 50m
          memory: 512Mi
        limits:
          memory: 1Gi
      route:
        enabled: true
        hostnames: ["{{ .Release.Name }}.480p.com"]
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
        matches:
          - path:
              type: PathPrefix
              value: "{{ .Values.authentik.web.path }}"