---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: authentik
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2025.4.1
  url: oci://ghcr.io/goauthentik/helm-charts/authentik
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app authentik
spec:
  driftDetection:
    mode: enabled
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: authentik
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    global:
      podAnnotations:
        reloader.stakater.com/auto: "true"
      deploymentStrategy:
        type: RollingUpdate
      envFrom:
        - secretRef:
            name: authentik-postgresql
    authentik:
      redis:
        host: dragonfly.dragonfly.svc.cluster.local
        port: 6379
        db: 1
      postgresql:
        host: pg17-rw.cnpg.svc.cluster.local
        port: 5432
        read_replicas:
          "0":
            host: pg17-r.cnpg.svc.cluster.local
            port: 5432
      primary:
        persistence:
          existingClaim: authentik
    server:
      initContainers:
        - name: init-db
          image: ghcr.io/home-operations/postgres-init:17.5@sha256:894a38169bf4135fb1e85a1112c64fc24a267d1191887cbf6fb8c0a17893770d
          envFrom:
            - secretRef:
                name: &secret authentik-postgresql
      replicas: 2
      resources:
        requests:
          cpu: 50m
          memory: 512Mi
        limits:
          memory: 1Gi
      # route:
      #   main:
      #     enabled: true
      #     hostnames: ["{{ .Release.Name }}.480p.com"]
      #     parentRefs:
      #       - name: external
      #         namespace: kube-system
      #         sectionName: https
      #     matches:
      #       - path:
      #           type: PathPrefix
      #           value: "{{ .Values.authentik.web.path }}"
