apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: &name authentik-postgres-v17
  namespace: &namespace authentik
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:17
  primaryUpdateStrategy: unsupervised
  storage:
    size: 2Gi
    storageClass: ceph-block
  resources:
    requests:
      memory: 800Mi
      cpu: 200m
    limits:
      memory: 2Gi
  enableSuperuserAccess: true
  managed:
    roles:
      - name: authentik
        login: true
        passwordSecret:
          name: authentik-postgresql
  superuserSecret:
    name: authentik-postgresql
  bootstrap:
    # use this to start a new cluster
    initdb:
      database: authentik
      owner: authentik
      secret:
        name: authentik-postgresql
