---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: huntarr-radarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: huntarr-radarr4k-secret
    template:
      engineVersion: v2
      data:
        API_KEY: "{{ .RADARR_API_KEY }}"
        API_URL: "http://radarr4k.media.svc.cluster.local:80"
  dataFrom:
    - extract:
        key: plex
    - extract:
        key: sonarr
    - extract:
        key: radarr
