---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app huntarr-radarr4k
spec:
  interval: 1h
  driftDetection:
    mode: enabled
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      huntarr-radarr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            envFrom:
              - secretRef:
                  name: huntarr-radarr4k-secret
            image:
              repository: huntarr/4radarr
              tag: latest@sha256:94ff228e8a2926313c2fc8188f7451831fb764ed3202dbf85323cdb407437c50
            probes:
              liveness: &probes
                enabled: true
              readiness: *probes
            # securityContext:
            #   allowPrivilegeEscalation: false
            #   readOnlyRootFilesystem: true
            #   capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
                memory: 512Mi

    # defaultPodOptions:
    #   securityContext:
    #     runAsNonRoot: true
    #     runAsUser: 1000
    #     runAsGroup: 1000
    #     fsGroup: 1000
    #     fsGroupChangePolicy: OnRootMismatch
    # service:
    #   app:
    #     controller: huntarr-radarr
    #     ports:
    #       http:
    #         port: &port 8988
    # ingress:
    #   app:
    #     enabled: true
    #     className: traefik
    #     annotations:
    #       external-dns.alpha.kubernetes.io/target: "480p.com"
    #       cert-manager.io/cluster-issuer: letsencrypt-production
    #       traefik.ingress.kubernetes.io/router.middlewares: network-authentik@kubernetescrd
    #     hosts:
    #       - host: &host "{{ .Release.Name }}.480p.com"
    #         paths:
    #           - path: /
    #             pathType: Prefix
    #             service:
    #               identifier: app
    #               port: *port
    #     tls:
    #       - hosts:
    #           - *host
    #         secretName: "{{ .Release.Name }}-tls"
    persistence:
      config:
        existingClaim: huntarr-radarr4k
      tmp:
        type: emptyDir
      # config:
      #   enabled: true
      #   type: secret
      #   name: huntarr-secret
      #   globalMounts:
      #     - path: /app/config.yaml
      #       subPath: config.yaml
