---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app debug-media
spec:
  driftDetection:
    mode: enabled
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      debug-media:
        type: deployment
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: alpine
              tag: latest

            command: ["sleep"]
            args: ["infinity"]
            # securityContext:
            #   allowPrivilegeEscalation: false
            #   readOnlyRootFilesystem: true
            #   capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                memory: 512Mi

    # defaultPodOptions:
    #   affinity:
    #     # Prefer to run on the same node as decypharr, but can run elsewhere if needed
    #     podAffinity:
    #       preferredDuringSchedulingIgnoredDuringExecution:
    #         - weight: 100
    #           podAffinityTerm:
    #             labelSelector:
    #               matchExpressions:
    #                 - key: app.kubernetes.io/instance
    #                   operator: In
    #                   values:
    #                     - decypharr
    #                 - key: app.kubernetes.io/component
    #                   operator: In
    #                   values:
    #                     - decypharr
    #             topologyKey: "kubernetes.io/hostname"
    #     # Also keep the node preference for realdebrid labeled nodes
    #     nodeAffinity:
    #       preferredDuringSchedulingIgnoredDuringExecution:
    #         - weight: 100
    #           preference:
    #             matchExpressions:
    #               - key: realdebrid
    #                 operator: Exists

    #   securityContext:
    #     runAsNonRoot: true
    #     runAsUser: 1000
    #     runAsGroup: 1000
    #     fsGroup: 1000
    #     fsGroupChangePolicy: OnRootMismatch
    persistence:
      symlinks:
        existingClaim: symlinks
        globalMounts:
          - path: /aio/symlinks
      rclone:
        existingClaim: pvc-rclone
        globalMounts:
          - path: /aio/remote/realdebrid
      # app:
      #   existingClaim: decypharr
