---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: debug-media-rolebinding
  namespace: media
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: debug-media-role
subjects:
- kind: ServiceAccount
  name: debug-media
  namespace: media