---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: tailscale
spec:
  interval: 2h
  url: https://pkgs.tailscale.com/helmcharts
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
spec:
  driftDetection:
    mode: enabled
  interval: 30m
  chart:
    spec:
      chart: tailscale-operator
      version: 1.84.0
      sourceRef:
        kind: HelmRepository
        name: tailscale
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    oauthSecretVolume:
      secret:
        secretName: oauth-client
    installCRDs: true
    ingressClass:
      enabled: true
    apiServerProxyConfig:
      mode: "true"
