---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: muse
  namespace: muse
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: muse
  interval: 1h
  path: ./kubernetes/apps/muse/muse/app
  postBuild:
    substitute:
      APP: muse
      # GATUS_PATH: /ready
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: muse
  timeout: 5m
  wait: false
