---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app muse
  namespace: &namespace muse
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: muse
  interval: 1h
  path: ./kubernetes/apps/muse/muse/app
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 3Gi
      VOLSYNC_SCHEDULE: "49 */3 * * *"
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
  components:
    - ../../../../components/gatus/guarded
    - ../../../../components/volsync
