---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-metadata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: ceph-block
