# https://github.com/onedr0p/home-ops
# gatewayAPI:
#   enabled: true
#   enableAlpn: true
#   xffNumTrustedHops: 1
# envoy:
#   rollOutPods: true
#   prometheus:
#     serviceMonitor:
#       enabled: true
# autoDirectNodeRoutes: true
# endpointRoutes:
#   enabled: true
# localRedirectPolicy: true

# https://github.com/michaelbeaumont/k8rn
ipam:
  mode: kubernetes
routingMode: native
ipv4NativeRoutingCIDR: "10.42.0.0/16"
ipv6:
  enabled: false # TODO when mayastor
kubeProxyReplacement: true
kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
envoy:
  baseID: 4244
hubble:
  relay:
    enabled: true
  ui:
    enabled: true
securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - PERFMON
      - BPF
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup
k8sServiceHost: localhost
k8sServicePort: 7445
extraInitContainers:
  - name: get-node-pod-cidr
    # image:
    # repository: docker.io/alpine/k8s
    # tag: 1.34.1@sha256:ec714df3813b5405292860f8a1c55c5727bf8c33c88992f1e981efad8065547f
    # image: mirror.gcr.io/alpine/k8s:1.34.1@sha256:ec714df3813b5405292860f8a1c55c5727bf8c33c88992f1e981efad8065547f
    image: alpine/k8s:1.34.1@sha256:ec714df3813b5405292860f8a1c55c5727bf8c33c88992f1e981efad8065547f
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: [ALL]
      runAsNonRoot: false
      readOnlyRootFilesystem: true
      seccompProfile:
        type: RuntimeDefault
    command: [sh, -c]
    args:
      - |
        set -e
        kubectl get nodes $(NODE_NAME) -o json > /mnt/share-pod-cidr/node_json
        cat /mnt/share-pod-cidr/node_json | jq -r '.spec.podCIDRs | join(",")' > /mnt/share-pod-cidr/out
    env:
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      - name: KUBERNETES_SERVICE_HOST
        value: "localhost"
      - name: KUBERNETES_SERVICE_PORT
        value: "7445"
    volumeMounts:
      - mountPath: /mnt/share-pod-cidr
        name: share-pod-cidr
  - name: set-tailscale-advertise-routes
    # image: mirror.gcr.io/tailscale/tailscale:latest@sha256:360e10ad95ad03950f66df03e0dab66287f9f89076ee4012d50bc6adceafcdf3
    image: tailscale/tailscale:latest@sha256:360e10ad95ad03950f66df03e0dab66287f9f89076ee4012d50bc6adceafcdf3
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: [ALL]
      runAsNonRoot: false
      readOnlyRootFilesystem: true
      seccompProfile:
        type: RuntimeDefault
    command: [sh, -c]
    args: ["tailscale set --advertise-routes $(cat /mnt/share-pod-cidr/out)"]
    volumeMounts:
      - mountPath: /var/run/tailscale/tailscaled.sock
        name: tailscaled-socket
      - mountPath: /mnt/share-pod-cidr
        name: share-pod-cidr
extraVolumes:
  - name: tailscaled-socket
    hostPath:
      path: /var/run/tailscale/tailscaled.sock
  - name: share-pod-cidr
    emptyDir: {}
