---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job.longhorn.io/backup-daily: enabled
    recurring-job.longhorn.io/snapshot-hourly: enabled
  name: sonarr-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
