---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: huntarr-sonarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: huntarr-sonarr-secret
    template:
      engineVersion: v2
      data:
        API_KEY: "{{ .SONARR_API_KEY }}"
        API_URL: "http://sonarr.media.svc.cluster.local:80"
        API_TIMEOUT: "60"
        MONITORED_ONLY: "true"
        HUNT_MISSING_SHOWS: "1"
        HUNT_UPGRADE_EPISODES: "0"
        SLEEP_DURATION: "900"
        STATE_RESET_INTERVAL_HOURS: "168"
        DEBUG_MODE: "false"
        ENABLE_WEB_UI: "true"
        SKIP_FUTURE_EPISODES: "true"
        SKIP_SERIES_REFRESH: "false"
        COMMAND_WAIT_DELAY: "1"
        COMMAND_WAIT_ATTEMPTS: "600"
        MINIMUM_DOWNLOAD_QUEUE_SIZE: "-1"
        RANDOM_MISSING: "true"
        RANDOM_UPGRADES: "true"
  dataFrom:
    - extract:
        key: plex
    - extract:
        key: sonarr
    - extract:
        key: radarr
