---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app muse
spec:
  driftDetection:
    mode: enabled
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: muse
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    defaultPodOptions:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
    controllers:
      muse:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            envFrom:
              - secretRef:
                  name: muse-secret
            image:
              repository: ghcr.io/museofficial/muse
              tag: pr-1284@sha256:67ef91ffc6a808feaec05bd7a1de8808cd5f100b588dcf1b522c704dcdcb9ba4
              # repository: ghcr.io/museofficial/muse
              # tag: latest@sha256:c666e6a2da22678e6fdd6dedae78c19e5029d22cc34e6379d98aa6e23ba09d2c
            env:
              TZ: Europe/Berlin
    #         securityContext: &securityContext
    #           allowPrivilegeEscalation: false
    #           readOnlyRootFilesystem: false
    #           capabilities: { drop: ["ALL"] }
    # defaultPodOptions:
    #   securityContext:
    #     runAsNonRoot: true
    #     runAsUser: 1000
    #     runAsGroup: 1000
    #     fsGroup: 1000
    #     fsGroupChangePolicy: OnRootMismatch
    # persistence:
    #   data:
    #     existingClaim: muse
