---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: longhorn
spec:
  interval: 2h
  url: https://charts.longhorn.io
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  driftDetection:
    mode: enabled
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: 1.8.1
      sourceRef:
        kind: HelmRepository
        name: longhorn
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    longhornUI:
      replicas: 2

    persistence:
      defaultClass: true
      defaultFsType: ext4
      defaultClassReplicaCount: 2
      defaultDataLocality: best-effort # best-effort otherwise
      defaultReplicaAutoBalance: best-effort # "disabled", "least-effort" or "best-effort" otherwise
      reclaimPolicy: Delete
      migratable: true
      allowVolumeExpansion: true

    defaultSettings:
      defaultDataPath: /var/lib/longhorn
      replicaSoftAntiAffinity: true
      replicaAutoBalance: least-effort
      storageOverProvisioningPercentage: 100
      storageMinimalAvailablePercentage: 25
      defaultReplicaCount: 2
      rwxVolumeFastFailover: true
      backupCompressionMethod: lz4
      backupConcurrentLimit: 2
      restoreConcurrentLimit: 2
      autoSalvage: true
      autoCleanupSystemGeneratedSnapshot: true
      autoCleanupRecurringJobBackupSnapshot: true
      logLevel: Info
      snapshotDataIntegrity: fast-check
      removeSnapshotsDuringFilesystemTrim: true
      disableRevisionCounter: true
      guaranteedInstanceManagerCPU: 12
      restoreVolumeRecurringJobs: false

    # -- Setting that allows you to update the default backupstore.
    defaultBackupStore:
      # -- Endpoint used to access the default backupstore.
      backupTarget: s3://longhorn@fra2/
      # -- Name of the Kubernetes secret associated with the default backup target.
      backupTargetCredentialSecret: longhorn-s3-backup-netdynamics
      # -- Number of seconds that Longhorn waits before checking the default backupstore for new backups.
      pollInterval: 300
