---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./s3-secret.sops.yaml
  - ./ts-ingress.yaml
  # - ./storageclasses.yaml
