apiVersion: v1
kind: Secret
metadata:
    name: longhorn-s3-backup
    namespace: longhorn-system
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:AEsqWHooH6zwdSPIvlPhBZv9qGk=,iv:eRN8JxkDgknImBosyCw0XZnTo6HK/yqi00PuI2ooRWQ=,tag:7PXBdjVR3deI0kcjUzWAXw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:6Ilp4iG9s2VlMBo/k1ZFPQp41NpkKKouBygLp+Fc/7stzRBJV+sLdw==,iv:+ccOHvQPETSmQ4FwDqD3XsVqG6bfA/Wq9VYsBjE9kYY=,tag:rd1uFB5Ni+51bOJ0P+8kLA==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:LagfGANA1LjohJ4sk8nXGyBSu+VdxQay8g==,iv:gaq9LBtMrU+c/bmpL2PpNvu0P4k6oMdsOEKaYZsvGDI=,tag:bXUiaOHUGFfC6ZisxdamDA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age127k9xyyfucv49hz4lgqyxhv3egulzyuvjaq9z099027jynczvslqvkn9cg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFN1gvcmVCQXZjV3Bka3hE
            ZVlUT2VTVVR3SCtXMTVPa0NSVXRxUGlkcVY0CmZCQTIrcXNxSTVyOVpGb0JKcURs
            eGFBZTdvdWEzaEs4b09FdGEvRW53dVEKLS0tIFNKVzFEdHBHd3NRRmVUaG9jbUZK
            MDQwVFJFb1FVUDZZWG1peWMwZ0d4cTgKrxdMGrdV3iVSLsYLLfnZX7cuItMMDRyR
            NWoCXAuh9PHwfbAioukdSPy4T+BArTqXxGZf+GEC3mNKl4bBDe2s+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-27T11:15:58Z"
    mac: ENC[AES256_GCM,data:X37XwI4tHkLiDfRUyFRSa9Fs7a2jeVzKCEab9/sV2jKKVkjdtRlFwOF9bdjsh/3kXkchjLDXqNbq+ZYE1HG7x7cGA3na2Km9BtvM9dxzNq8Lu+BYxKVyTzLDt+8rPdOyy/NuOzoByjtWzYkLA5O4MhcaVsjD8/p3SdWNblQFnXA=,iv:ZQhd1FO5pZmhYzXidtU3c0AOqIpHmA+NrFsTPtW0EDw=,tag:PqE+A24YZwM5lmbLKeGlDg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
