---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-rc1
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
  fsType: "ext4"
  dataLocality: "best-effort"
  replicaAutoBalance: "least-effort"
  recurringJobSelector: '[{"name":"longhorn-rc1", "isGroup":true}]'
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-rc2
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "30"
  fsType: "ext4"
  dataLocality: "best-effort"
  replicaAutoBalance: "least-effort"
  recurringJobSelector: '[{"name":"longhorn-rc2", "isGroup":true}]'

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-rc3
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  fsType: "ext4"
  dataLocality: "best-effort"
  replicaAutoBalance: "least-effort"
  recurringJobSelector: '[{"name":"longhorn-rc3", "isGroup":true}]'
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-volsync
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
  fsType: "ext4"
  dataLocality: "best-effort"
  replicaAutoBalance: "least-effort"
  recurringJobSelector: '[{"name":"volsync-group", "isGroup":true}]'
