---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alloy
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: alloy-secret
    template:
      data:
        username: "{{ .ALLOY_USERNAME }}"
        password: "{{ .ALLOY_PASSWORD }}"
  dataFrom:
    - extract:
        key: alloy
