---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./radarr-secret.sops.yaml
  - ./pvc-cache.yaml
  - ./pvc-config.yaml
# configMapGenerator:
#   - name: radarr-configmap
#     files:
#       - codec-tagger.sh=./resources/codec-tagger.sh
#       - pushover-notifier.sh=./resources/pushover-notifier.sh
#       - tba-refresher.sh=./resources/tba-refresher.sh
#   - name: radarr-loki-rules
#     files:
#       - radarr.yaml=./lokirule.yaml
#     options:
#       labels:
#         loki_rule: "true"
# generatorOptions:
#   disableNameSuffixHash: true
#   annotations:
#     kustomize.toolkit.fluxcd.io/substitute: disabled