apiVersion: v1
data:
  RADARR__AUTH__APIKEY: ENC[AES256_GCM,data:rm/derk1O4eSLwDUkj0OveB8ceMdxVLaktlZ7Pp/OabiEXwRIPSFyg==,iv:C5pmPdqfYVQRP7TZXGkzABytqJNJ3tfAEWZlDWyKS/4=,tag:0NE9bMmJj2dKZWlc5dP3bQ==,type:str]
kind: Secret
metadata:
  creationTimestamp: null
  name: radarr-secret
  namespace: media
sops:
  age:
    - recipient: age127k9xyyfucv49hz4lgqyxhv3egulzyuvjaq9z099027jynczvslqvkn9cg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxRjllOHdvRURtemxxWDBQ
        NFRSalFpbytKRnNHNTBQeTNuaFVDRXNpVlhnCkE4R29COXZsTUt2ckh5UUJMcits
        b2lCc2Y5YWc1c2xVd3h1OTdtT1BOdWcKLS0tIFFVQmE2SGFlaE5KVnVwM093Yjkr
        YXJvQmZXQnp0UVZJQkhLM21aMjBpLzgK3Wypsr0F3+bIc8PNHQzJkrN7eoI+u7hj
        5N9UG+jrIFhenynqKb9oDzb+SZCDM/87s4XNyu+jOZ/hMQkboRqj0g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-31T18:29:15Z"
  mac: ENC[AES256_GCM,data:xO2yh6y/FPGz8jNg8rvR9qVzpJUxaOibD1Pq+XYRs+p+lSaZX0SN3JFfjsieMzubU3xArDjM/CrEY5wH0/sadJmcwhagsFQKqTqrQwDMtspgPxtcarF775b+ZY7ItsXtHY5t/UTA+2Ao9ClI1h7IiI67H1Dqml1hrb9cZGYN27Y=,iv:LCmAyUUVTqgA6f5ikAXq2uJDyYFVjvhL/vTPDjhlsA8=,tag:Y3Hp3k6/ALAzyTsSjWf6MA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.0
