---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: snapshot-daily
  namespace: longhorn-system
spec:
  cron: "0 4 * * *"
  task: "snapshot"
  groups:
    - default
    - backup-s3-daily
  retain: 20
  concurrency: 2
