---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dragonfly
  namespace: dragonfly
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: dragonfly
  interval: 1h
  path: ./kubernetes/apps/dragonfly/dragonfly/app
  postBuild:
    substitute:
      APP: dragonfly
      # GATUS_PATH: /ready
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: dragonfly
  timeout: 5m
  wait: false
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dragonfly-cluster
  namespace: dragonfly
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: dragonfly-cluster
  interval: 1h
  path: ./kubernetes/apps/dragonfly/dragonfly/cluster
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: dragonfly
  timeout: 5m
  wait: false
