---
web:
  port: ${GATUS_WEB_PORT}

metrics: true

ui:
  title: Status | Gatus
  header: Status
  logo: https://avatars.githubusercontent.com/u/20051140
  link: https://github.com/herobrauni
  buttons:
    - name: Github
      link: https://github.com/herobrauni
    - name: Homelab
      link: https://github.com/herobrauni/k

connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m

endpoints:
  - name: flux-webhook
    group: external
    url: https://flux-webhook.480p.com
    interval: 1m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == 404"
