---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-env-secrets
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: oauth2-proxy-env-secrets
    template:
      data:
        OAUTH2_PROXY_CLIENT_ID: "{{ .OAUTH2_PROXY_CLIENT_ID }}"
        OAUTH2_PROXY_CLIENT_SECRET: "{{ .OAUTH2_PROXY_CLIENT_SECRET }}"
        OAUTH2_PROXY_COOKIE_SECRET: "{{ .OAUTH2_PROXY_COOKIE_SECRET }}"
  dataFrom:
    - extract:
        key: oauth2-proxy
