---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secrets-writer
  namespace: obs2
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-writer
  namespace: obs2
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secrets-writer
  namespace: obs2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secrets-writer
subjects:
- kind: ServiceAccount
  name: secrets-writer