---
clusterName: k2
endpoint: https://k2-talos.480p.com:6443

allowSchedulingOnMasters: true
allowSchedulingOnControlPlanes: true
additionalApiServerCertSans:
  - k2-talos.480p.com
clusterPodNets:
  - 10.42.0.0/16
clusterSvcNets:
  - 10.43.0.0/16
cniConfig:
  name: none

domain: cluster.local
nodes:
  - hostname: gc1
    controlPlane: true
    ipAddress: 92.118.190.11
    installDiskSelector:
      size: <= 300GB
    networkInterfaces:
      - interface: ens3
        addresses:
          - 92.118.190.11/24
        dhcp: false
        routes:
          - gateway: 92.118.190.1
    certSANs:
      - gc1.brill-bebop.ts.net
      - gc1

  - hostname: gc5
    controlPlane: true
    ipAddress: 109.94.170.65
    installDiskSelector:
      size: <= 300GB
    networkInterfaces:
      - interface: ens3
        addresses:
          - 109.94.170.65/24
        dhcp: false
        routes:
          - gateway: 109.94.170.1
    certSANs:
      - gc5.brill-bebop.ts.net
      - gc5

  - hostname: gc7
    controlPlane: true
    ipAddress: 92.118.190.62
    installDiskSelector:
      size: <= 300GB
    networkInterfaces:
      - interface: ens3
        addresses:
          - 92.118.190.62/24
        dhcp: false
        routes:
          - gateway: 92.118.190.1
    certSANs:
      - gc7.brill-bebop.ts.net
      - gc7

patches:
  - |-
    machine:
      network:
        nameservers:
          - fd7a:115c:a1e0::53 # tailscale dns
          - 2606:4700:4700::1111 # cloudflare 1111
          - 1.1.1.1

  - |-
    machine:
      kubelet:
        nodeIP:
          validSubnets:
            - 100.64.0.0/10
        extraArgs:
            rotate-server-certificates: true
      time:
        servers:
          - time.cloudflare.com

  - |-
    cluster:
      discovery:
        enabled: false
  - |-
    machine:
      install:
        wipe: false
      features:
        rbac: true
        stableHostname: true
  - |-
    cluster:
      coreDNS:
        disabled: true
      proxy:
        disabled: true
      apiServer:
        admissionControl:
          - name: PodSecurity
            configuration:
              apiVersion: pod-security.admission.config.k8s.io/v1alpha1
              defaults:
                audit: restricted
                audit-version: latest
                enforce: privileged
                enforce-version: latest
                warn: restricted
                warn-version: latest
              # don't add any exemptions
              kind: PodSecurityConfiguration

controlPlane:
  extraManifests:
    - ./volumeconfig.yaml
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
          - siderolabs/tailscale
          - siderolabs/qemu-guest-agent
  patches:
    - |-
      etcd:
        advertisedSubnets:
          - 100.64.0.0/10
    - |-
      - op: remove
        path: /machine/nodeLabels/node.kubernetes.io~1exclude-from-external-load-balancers
    - |-
      - op: remove
        path: /cluster/apiServer/admissionControl
    - |-
      cluster:
        etcd:
          extraArgs:
            listen-metrics-urls: http://0.0.0.0:2381
    - |-
      machine:
        features:
          kubernetesTalosAPIAccess:
            enabled: true
            allowedRoles: ["os:admin"]
            allowedKubernetesNamespaces: ["actions-runner-system", "system-upgrade"]
worker:
  extraManifests:
    - ./volumeconfig.yaml
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
          - siderolabs/qemu-guest-agent
