---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: huntarr-sonarr4k
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: huntarr-sonarr4k-secret
    template:
      engineVersion: v2
      data:
        API_KEY: "{{ .SONARR_API_KEY }}"
        API_URL: "http://sonarr4k.media.svc.cluster.local:80"
        HUNT_MISSING_SHOWS: "10"
  dataFrom:
    - extract:
        key: plex
    - extract:
        key: sonarr
    - extract:
        key: radarr
