apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: network
spec:
  valuesContent: |-
    service:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: "${SECRET_DOMAIN}"
