---
originRequest:
  originServerName: traefik.480p.com

ingress:
  - hostname: 480p.com
    service: &svc https://traefik.kube-system.svc.cluster.local
  - hostname: "*.480p.com"
    service: *svc
  - service: http_status:404
