---
# originRequest:
#   originServerName: 480p.com
noTLSVerify: true
ingress:
  - hostname: 480p.com
    service: &svc http://traefik.network.svc.cluster.local
  - hostname: "*.480p.com"
    service: *svc
  - service: http_status:404
