---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: renku
spec:
  interval: 5m
  url: https://swissdatasciencecenter.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-rclone
spec:
  driftDetection:
    mode: enabled
  interval: 30m
  timeout: 5m
  chart:
    spec:
      chart: csi-rclone
      version: 0.4.2
      sourceRef:
        kind: HelmRepository
        name: renku
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    csiControllerRclone:
      rclone:
        image:
          repository: ghcr.io/herobrauni/csi-rclone
          tag: latest@sha256:93edcf398b0866e641b183a8b341cd06942c1a24bb075ec9dec8caf5c9d5f9d7
        imagePullPolicy: IfNotPresent

    csiNodepluginRclone:
      rclone:
        image:
          repository: ghcr.io/herobrauni/csi-rclone
          tag: latest@sha256:93edcf398b0866e641b183a8b341cd06942c1a24bb075ec9dec8caf5c9d5f9d7
        imagePullPolicy: IfNotPresent
