---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: renku
spec:
  interval: 5m
  url: https://swissdatasciencecenter.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-rclone
spec:
  driftDetection:
    mode: enabled
  interval: 30m
  timeout: 5m
  chart:
    spec:
      chart: csi-rclone
      version: 0.4.2
      sourceRef:
        kind: HelmRepository
        name: renku
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    rclone:
      image:
        repository: csi-rclone
        tag: latest@sha256:6344c9e720470e29d3ee47c194f8e33c25e3a87377facc95b52e0b0204b14e30
      imagePullPolicy: IfNotPresent
