---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: autosync
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: autosync-secret
    template:
      engineVersion: v2
      data:
        # The complete YAML config file
        config.yaml: |
          webhook_events:
            sonarr:
              - Grab
              - Download
              - Rename
              - SeriesDelete
              - EpisodeFileDelete
              - Import
            radarr:
              - Grab
              - Download
              - Rename
              - MovieDelete
              - MovieFileDelete
              - Import
          media_servers:
            - name: instance_name
              type: plex
              url: 'http://plex.media.svc.cluster.local:32400'
              token: '{{ .PLEX_TOKEN }}'
              enabled: true
          # instances:
            # - name: sonarr
            #   type: sonarr
            #   url: 'http://sonarr.media.svc.cluster.local'
            #   api_key: '{{ .SONARR_API_KEY }}'
            #   root_folder_path: /aio/symlinks/plex_hd/shows
            #   season_folder: true
            #   quality_profile_id: 7
            #   language_profile_id: 1
            #   search_on_sync: true
            #   enabled_events:
            #     # - Grab
            #     # - Download
            #     # - Rename
            #     # - SeriesDelete
            #     # - EpisodeFileDelete
            #     - Import
            # - name: sonarr4k
            #   type: sonarr
            #   url: 'http://sonarr4k.media.svc.cluster.local'
            #   api_key: '{{ .SONARR_API_KEY }}'
            #   root_folder_path: /aio/symlinks/plex_4k/shows
            #   season_folder: true
            #   quality_profile_id: 7
            #   language_profile_id: 1
            #   search_on_sync: true
            #   enabled_events:
            #     - Grab
            #     # - Download
            #     # - Rename
            #     # - SeriesDelete
            #     # - EpisodeFileDelete
            #     - Import
            # - name: instance_name
            #   type: radarr
            #   url: 'http://radarr.media.svc.cluster.local'
            #   api_key: '{{ .RADARR_API_KEY }}'
            #   root_folder_path: /aio/symlinks/plex_hd/movies
            #   quality_profile_id: 7
            #   search_on_sync: true
            #   enabled_events:
            #     # - Grab
            #     # - Download
            #     # - Rename
            #     # - MovieDelete
            #     # - MovieFileDelete
            #     - Import
            # - name: radarr4k
            #   type: radarr
            #   url: 'http://radarr4k.media.svc.cluster.local'
            #   api_key: '{{ .RADARR_API_KEY }}'
            #   root_folder_path: /aio/symlinks/plex_4k/movies
            #   quality_profile_id: 7
            #   search_on_sync: true
            #   enabled_events:
            #     - Grab
            #     # - Download
            #     # - Rename
            #     # - MovieDelete
            #     # - MovieFileDelete
            #     - Import
  dataFrom:
    - extract:
        key: plex
    - extract:
        key: sonarr
    - extract:
        key: radarr
