---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/ocirepository-source-v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: traefik
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 35.2.0
  url: oci://ghcr.io/traefik/helm/traefik
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
spec:
  driftDetection:
    mode: enabled
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: traefik
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    gatewayClass:
      enabled: true
      name: traefik-gateway-class
    providers:
      kubernetesGateway:
        # -- Enable Traefik Gateway provider for Gateway API
        enabled: true
        # -- Toggles support for the Experimental Channel resources (Gateway API release channels documentation).
        # This option currently enables support for TCPRoute and TLSRoute.
        experimentalChannel: true
      kubernetesCRD:
        enabled: true
        allowExternalNameServices: true
        allowCrossNamespace: true
    kubernetesIngress:
      enabled: true
      allowExternalNameServices: true
      allowCrossNamespace: true
      ingressClass: traefik
    ports:
      traefik:
        expose:
          default: true
      # Entrypoints
      web:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
        advertisedPort: 80
    service:
      enabled: true
      type: ClusterIP
      annotations:
        external-dns.alpha.kubernetes.io/hostname: "480p.com"

      websecure:
        tls:
          enabled: true
          options: "default"
    fullnameOverride: traefik

    globalArguments:
      - "--global.checknewversion=false"
      - "--global.sendanonymoususage=false"
      - "--api.insecure=true"
      - "--serverstransport.insecureskipverify=true"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.entryPoint=metrics"
