---
groups:
  - name: radarr4k
    rules:
      - alert: radarr4kDatabaseIsLocked
        expr: |
          sum by (app) (count_over_time({app=~"radarr4k"} |~ "(?i)database is locked"[5m])) > 0
        for: 5m
        annotations:
          summary: >-
            {{ $labels.app }} is experiencing database issues
        labels:
          severity: critical

      - alert: radarr4kDatabaseIsMalformed
        expr: |
          sum by (app) (count_over_time({app=~"radarr4k"} |~ "(?i)database disk image is malformed"[5m])) > 0
        for: 5m
        annotations:
          summary: >-
            {{ $labels.app }} is experiencing database issues
        labels:
          severity: critical
