---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: flannel
spec:
  interval: 2h
  url: https://flannel-io.github.io/flannel/
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flannel
spec:
  driftDetection:
    mode: enabled
  interval: 30m
  chart:
    spec:
      chart: flannel
      version: 0.26.7
      sourceRef:
        kind: HelmRepository
        name: flannel
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    podCidr: 10.42.0.0/16
