---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: 480p-com-tls
spec:
  secretStoreRefs:
    - name: bitwarden-secretsmanager
      kind: ClusterSecretStore
  selector:
    secret:
      name: 480p-com-tls
  template:
    engineVersion: v2
    data:
      tls.crt: '{{ index . "tls.crt" | b64enc }}'
      tls.key: '{{ index . "tls.key" | b64enc }}'
  data:
    - match:
        secretKey: &key tls.crt
        remoteRef:
          remoteKey: 480p-com-tls
          property: *key
    - match:
        secretKey: &key tls.key
        remoteRef:
          remoteKey: 480p-com-tls
          property: *key
