---
apiVersion: v1alpha1
kind: NetworkDefaultActionConfig
ingress: block
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: kubelet-ingress
portSelector:
  ports:
    - 10250
    - 10257
    - 10259
  protocol: tcp
ingress:
  - subnet: "100.99.99.0/24"
  - subnet: "10.42.0.0/16"
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: apid-ingress
portSelector:
  ports:
    - 50000
  protocol: tcp
ingress:
  - subnet: 100.64.0.0/10
  - subnet: fd7a:115c:a1e0::/48
  - subnet: 0.0.0.0/0
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: trustd-ingress
portSelector:
  ports:
    - 50001
  protocol: tcp
ingress:
  - subnet: "100.99.99.0/24"
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: kubernetes-api-ingress
portSelector:
  ports:
    - 6443
  protocol: tcp
ingress:
  - subnet: 100.64.0.0/10
  - subnet: fd7a:115c:a1e0::/48
  - subnet: "10.42.0.0/16"
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: etcd-ingress
portSelector:
  ports:
    - 2379-2380
  protocol: tcp
ingress:
  - subnet: "100.99.99.0/24"
  - subnet: "10.42.0.0/16"
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: cilium-health
portSelector:
  ports:
    - 4240
  protocol: tcp
ingress:
  - subnet: "100.99.99.0/24"
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: kubelet-pod-ingress
portSelector:
  ports:
    - 10250
  protocol: tcp
ingress:
  - subnet: "10.42.0.0/16"
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: node-exporter-ingress
portSelector:
  ports:
    - 9100
  protocol: tcp
ingress:
  - subnet: "100.99.99.0/24"
  - subnet: "10.42.0.0/16"
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: hubble
portSelector:
  ports:
    - 4244
    - 4245
  protocol: tcp
ingress:
  - subnet: "100.99.99.0/24"
  - subnet: "10.42.0.0/16"
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: spegel
portSelector:
  ports:
    - 29999
  protocol: tcp
ingress:
  - subnet: "100.99.99.0/24"
  - subnet: "10.42.0.0/16"
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: ceph
portSelector:
  ports:
    - 3300
    - 6800-7300
  protocol: tcp
ingress:
  - subnet: "100.99.99.0/24"
  - subnet: "10.42.0.0/16"
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: Ceph-Metrics
portSelector:
  ports:
    - 9080
    - 9926
    - 9283
  protocol: tcp
ingress:
  - subnet: "100.99.99.0/24"
  - subnet: "10.42.0.0/16"
