---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job.longhorn.io/backup-daily: enabled
    recurring-job.longhorn.io/snapshot-hourly: enabled
  name: rdtclient-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
