name: Build and Publish csi-rclone Docker Images

on:
  schedule:
    # Run weekly on Mondays at 3:00 AM UTC
    - cron: '0 3 * * 1'
  workflow_dispatch:
    # Allow manual triggering

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Clone source repository
        run: |
          git clone https://github.com/SwissDataScienceCenter/csi-rclone.git src-repo
          echo "Cloned repository contents:"
          ls -la src-repo/

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Chartpress
        run: |
          pip install chartpress
          chartpress --version

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build images with Chartpress
        run: |
          cd src-repo
          echo "Running chartpress to build images..."
          chartpress --builder docker-buildx --platform linux/amd64 --platform linux/arm64
        env:
          # Ensure images are tagged correctly
          DOCKER_REGISTRY: ghcr.io/${{ github.repository_owner }}

      - name: List built images
        run: |
          echo "Built Docker images:"
          docker images --format "table {{.Repository}}:{{.Tag}}\t{{.CreatedAt}}\t{{.Size}}" | grep -E "(csi-rclone|ghcr.io)"

      - name: Push images to GitHub Container Registry
        run: |
          echo "Pushing images to GHCR..."
          # Get all images that match the GHCR pattern
          for image in $(docker images --format "{{.Repository}}:{{.Tag}}" | grep "ghcr.io/${{ github.repository_owner }}"); do
            echo "Pushing $image"
            docker push "$image"
          done

      - name: Summary
        run: |
          echo "✅ Successfully built and published Docker images using Chartpress"
          echo "📦 Images published to: ghcr.io/${{ github.repository_owner }}"
          echo "🏷️  Tags: Versioned tags as defined in chartpress.yaml"