---
    name: "Renovate"

    on: # <- when this action should run
      workflow_dispatch: # <- this allows you to run it manually

      schedule: # <- we will run it on a schedule
        - cron: "0 * * * *" # Every hour
      push: # <- run if we update the configuration
        branches: ["main"]
        paths:
          - .github/renovate.json5

    permissions: # <- set permissions for the default github token
      packages: read

    concurrency: # <- ensure workflow triggers are handled concurrently
      group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
      cancel-in-progress: true

    env: # <- define some env variables
      LOG_LEVEL: "debug" # <- info or debug
      RENOVATE_AUTODISCOVER: true # <- let renovate discover your repositoties
      RENOVATE_AUTODISCOVER_FILTER: "${{ github.repository }}" # <- limit to this repo only
      RENOVATE_PLATFORM: github # <- pretty obvious
      RENOVATE_PLATFORM_COMMIT: true # <- This will allow the bot to sign the commits (using the private key we just created)
      RENOVATE_BOT_NAME: 'bb-17' # <- my bot name, change this for your bot
      RENOVATE_HOST_RULES: | # private registries/repos <- needed to pass the github token to renovate
        [{"hostType": "docker", "matchHost": "ghcr.io", "username": "${{ github.actor }}", "password": "${{ secrets.GITHUB_TOKEN }}"}]

    jobs:
      renovate:
        name: Renovate
        runs-on: ubuntu-latest
        steps:
          - name: Generate Token # <- Generate an access token for the bot
            uses: actions/create-github-app-token@v1
            id: app-token
            with:
              app-id: "${{ secrets.BOT_APP_ID }}" # <- Change this if you called the secret something else
              private-key: "${{ secrets.BOT_PRIVATE_KEY }}" # <- Change this if you called the secret something else

          - name: Checkout
            uses: actions/checkout@v4
            with:
              token: "${{ steps.app-token.outputs.token }}" # <- we are using the generated token

          - name: Renovate # <- Run Renovate
            uses: renovatebot/github-action@v40.3.6
            with:
              configurationFile: .github/renovate.json
              token: "${{ steps.app-token.outputs.token }}"